# Generated by Django 6.0.3 on 2026-03-25 05:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektor', models.CharField(choices=[('SDP', 'Sektor Dasar & Penyelidikan (SDP)'), ('SSJ', 'Sektor Dasar Jaminan Kualiti (SSJ)'), ('KSP', 'Kumpulan Sektor Profesional (KSP)'), ('KN', 'Ketua Nazir (KN)'), ('SDTM', 'Sektor Dasar & Teknologi Maklumat (SDTM)'), ('SPK', 'Sektor Pembangunan Karakter (SPK)'), ('SPI', 'Sektor Pembelajaran & Inovasi (SPI)'), ('PS', 'Sektor Pengurusan Sekolah (PS)'), ('HEM', 'Sektor Hal Ehwal Murid (HEM)'), ('K', 'Sektor Kewangan/Korporat (K)')], max_length=10)),
                ('nama_program', models.CharField(max_length=200)),
                ('kod_aktiviti', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('no_ic', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('peranan', models.CharField(default='user', max_length=20)),
                ('sektor', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tuntutan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh_mohon', models.DateTimeField(auto_now_add=True)),
                ('jenis_pemohon', models.CharField(choices=[('individu', 'Individu'), ('organisasi', 'Organisasi')], default='individu', max_length=20)),
                ('nama_manual', models.CharField(max_length=255)),
                ('ic_manual', models.CharField(max_length=50)),
                ('sektor_manual', models.CharField(blank=True, max_length=100)),
                ('kod_aktiviti_auto', models.CharField(max_length=20)),
                ('e21101', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('e21102', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('e21103', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('e21104', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('e21105', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('e21106', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('e21199', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('keterangan', models.TextField(blank=True)),
                ('tarikh_mula', models.DateField(blank=True, null=True)),
                ('tarikh_tamat', models.DateField(blank=True, null=True)),
                ('jumlah_tuntut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('proses', 'Dalam Proses'), ('lulus', 'Lulus'), ('reject', 'Ditolak')], default='proses', max_length=20)),
                ('ulasan_admin', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
