# Generated by Django 6.0.3 on 2026-03-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='kod_aktiviti',
        ),
        migrations.RemoveField(
            model_name='program',
            name='nama_program',
        ),
        migrations.RemoveField(
            model_name='tuntutan',
            name='tarikh_mula',
        ),
        migrations.RemoveField(
            model_name='tuntutan',
            name='tarikh_tamat',
        ),
        migrations.AddField(
            model_name='program',
            name='bilangan_peserta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='gred_pegawai',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='justifikasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='nama_event',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='os21000_a1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='pegawai_bertanggungjawab',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='peruntukan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='status_pelaksanaan',
            field=models.CharField(choices=[('belum', 'Belum Bermula'), ('berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai'), ('pinda', 'Dipinda'), ('batal', 'Dibatalkan')], default='belum', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='tarikh_mula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tarikh_tamat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='unit',
            field=models.CharField(default='Program Baru', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='peranan',
            field=models.CharField(choices=[('user', 'Pegawai Biasa'), ('ptdm', 'PTDM (Data Management)'), ('peneraju', 'Peneraju Sektor'), ('kewangan', 'Unit Kewangan')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='sektor',
            field=models.CharField(choices=[('SDP', 'Sektor Dasar & Perancangan (SDP)'), ('SSJK', 'Sektor Sekolah Jenis Kebangsaan (SSJK)'), ('SPKN', 'Sektor Pendidikan Khas (SPKN)'), ('SDTM', 'Sektor Digital & Teknologi Maklumat (SDTM)'), ('SPK', 'Sektor Pengurusan Kualiti (SPK)'), ('SPIP', 'Sektor Pembelajaran & Integriti (SPIP)'), ('SPHEMK', 'Sektor Hal Ehwal Murid & Kaunseling (SPHEMK)'), ('SP', 'Sektor Pentadbiran (SP)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tuntutan',
            name='kod_aktiviti_auto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tuntutan',
            name='status',
            field=models.CharField(choices=[('proses', 'Dalam Proses'), ('disokong', 'Disokong Peneraju'), ('lulus', 'Lulus'), ('reject', 'Ditolak')], default='proses', max_length=20),
        ),
    ]
