# Generated by Django 6.0.3 on 2026-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_remove_program_kod_aktiviti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gambar',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gred',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
