# Generated by Django 6.0.3 on 2026-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_customuser_gambar_customuser_gred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gambar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
