# Generated by Django 6.0.3 on 2026-04-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_customuser_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='os21000_b1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='os24000_a2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='os24000_b2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='os27000_a3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='os27000_b3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='os29000_a4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='os29000_b4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='program',
            name='gred_pegawai',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='sektor',
            field=models.CharField(choices=[('SP', 'SEKTOR PENGURUSAN'), ('SDP', 'SEKTOR DASAR DAN PERANCANGAN'), ('SSJK', 'SEKTOR STANDARD DAN JAMINAN KUALITI'), ('SDTM', 'SEKTOR DATA DAN TEKNOLOGI MAKLUMAT'), ('SPKN', 'SEKTOR PEMBANGUNAN KOMPETENSI NAZIR'), ('SPK', 'SEKTOR PENAZIRAN KURIKULUM'), ('SPIP', 'SEKTOR PENAZIRAN INSTITUSI PENDIDIKAN'), ('SPHEMK', 'SEKTOR PENAZIRAN HAL EHWAL MURID DAN KOKURIKULUM'), ('JN_PERLIS', 'JN NEGERI PERLIS'), ('JN_KEDAH', 'JN NEGERI KEDAH'), ('JN_PP', 'JN NEGERI PULAU PINANG'), ('JN_PERAK', 'JN NEGERI PERAK'), ('JN_KELANTAN', 'JN NEGERI KELANTAN'), ('JN_TERENGGANU', 'JN NEGERI TERENGGANU'), ('JN_PAHANG', 'JN NEGERI PAHANG'), ('JN_SELANGOR', 'JN NEGERI SELANGOR'), ('JN_MELAKA', 'JN NEGERI MELAKA'), ('JN_NS', 'JN NEGERI NEGERI SEMBILAN'), ('JN_JOHOR', 'JN NEGERI JOHOR'), ('JN_WPKL', 'JN WILAYAH PERSEKUTUAN KUALA LUMPUR'), ('JN_SABAH', 'JN NEGERI SABAH'), ('JN_SARAWAK', 'JN NEGERI SARAWAK'), ('JN_TAWAU', 'JN CAWANGAN TAWAU, SABAH'), ('JN_KENINGAU', 'JN CAWANGAN KENINGAU, SABAH'), ('JN_SANDAKAN', 'JN CAWANGAN SANDAKAN, SABAH'), ('JN_MIRI', 'JN CAWANGAN MIRI, SARAWAK'), ('JN_SIBU', 'JN CAWANGAN SIBU, SARAWAK'), ('JN_BINTULU', 'JN CAWANGAN BINTULU, SARAWAK')], max_length=50),
        ),
    ]
