# Generated by Django 6.0.3 on 2026-04-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_program_os21000_b1_program_os24000_a2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='jenis_tugas',
            field=models.CharField(default='Mesyuarat', max_length=100),
        ),
    ]
