# Generated by Django 6.0.3 on 2026-04-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_program_jenis_tugas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='peruntukan',
            field=models.CharField(default='DSA (JN)', max_length=255),
        ),
    ]
