# Generated by Django 6.0.3 on 2026-04-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_alter_program_peruntukan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='jenis_tugas',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='peruntukan',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
