# Generated by Django 6.0.3 on 2026-04-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_alter_program_sektor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuntutan',
            name='jumlah_diluluskan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
