# Generated by Django 6.0.3 on 2026-04-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_tuntutan_jumlah_diluluskan'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='kod_aktiviti',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
