# Generated by Django 6.0.3 on 2026-04-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_alter_tuntutan_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuntutan',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tuntutan', to='claims.program'),
        ),
    ]
